repos:

  - repo: local
    hooks:
      - id: validate-cff
        name: Validating CITATION.cff using 'cffconvert'
        entry: cffconvert --validate
        language: system
        pass_filenames: false
        files: ^CITATION\.cff$

  - repo: https://github.com/regebro/pyroma
    rev: "5.0.1"
    hooks:
      - id: pyroma
        name: Assessing the package metadata using 'pyroma'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.3
    hooks:
      - id: ruff-check
        name: Linting using 'ruff'

  - repo: https://github.com/tcort/markdown-link-check
    rev: bde6fd2675901c55f8a356a67475257d44af51ae # 3.11.2
    hooks:
      - id: markdown-link-check
        args: [-q]
