name: cffconvert

on:
  push:
    paths:
      - CITATION.cff
  workflow_dispatch:

jobs:
  validate:
    name: "validate"
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v7.0.1

      - name: Build the current cffconvert image
        run: docker build --tag cffconvert .

      - name: Check whether the citation metadata from CITATION.cff is valid
        run: docker run --rm -v "$GITHUB_WORKSPACE:/work" -w /work cffconvert --validate
